# Simetria de funções

::: {.definition name="Domínio simétrico em relação à origem" #defsimetriaorigem}
Seja \( f: \mathbb{R} \rightarrow \mathbb{R} \), dizemos que \(f\) tem domínio simétrico em relação à origem se, e somente se, \( \forall x \in Df \Leftrightarrow -x \in Df \)
:::

::: {.definition name="Função par e ímpar" #defparimpar}
Seja a função real \(f\) com domínio simétrico na origem, temos que:

- \(f(x)\) é **par** \(\Leftrightarrow f(x) = f(-x)\)
- \(f(x)\) é **ímpar** \(\Leftrightarrow f(x) = -f(-x)\)
:::

## Propriedades

Sejam \(\jmath\) e \(\Im\) classes de funções tal que \(\forall f \in \jmath\) é par e \(\forall g \in \Im\) é ímpar, temos as seguintes propriedades.

::: {.theorem name="Elemento oposto"}
\(f(x) - f(-x) = 0\) e \(g(x)+g(-x)=0\)
:::

::: {.theorem name="Somas internas à classe"}
**1)** \(f_i(x) + f_j(x) \in \jmath\) e \(f_i(x) - f_j(x) \in \jmath\)

**2)** \(g_i(x) + g_j(x) \in \Im\) e \(g_i(x) - g_j(x) \in \Im\)
:::

::: {.proof}
\[
h(x) = f_i(x)+f_j(x)=f_i(-x)+f_j(-x)=h(-x)
\]

\[
h(x) = f_i(x)-f_j(x) = f_i(-x)-f_j(-x)=h(-x)
\]

\[
h(x)=g_i(x)+g_j(x)=-g_i(-x)-g_j(-x)=-h(-x)
\]

\[
h(x)=g_i(x)-g_j(x)=g_i(x)+g_j(-x)=-h(-x)
\]
:::

::: {.theorem name="Produto interno à classe"}
\(f_i(x)f_j(x) \in \jmath\) e \(g_i(x)g_j(x) \in \jmath\)
:::

::: {.proof}
\[
f_i(x)f_j(x) = f_i(-x)f_j(-x)
\]

\[
g_i(x)g_j(x)=(-g_i(-x))(-g_j(-x))=g_i(-x)g_j(-x)
\]
:::

::: {.theorem name="Produto interclasse"}
\(f(x)g(x) \in \Im\)
:::

::: {.proof}
\[
fg(x) = f(x)g(x)=f(-x)(-g(-x))=-fg(-x)
\]
:::

::: {.theorem name="Soma interclasse"}
Se \(\operatorname{Im} f \neq 0\) e \(\operatorname{Im} g \neq 0\), então seja \(h(x) = f(x) + g(x)\), temos que \(h(x) \notin \jmath\) e \(h(x) \notin \Im\)
:::

::: {.proof}
\[
h(x) = f(x) + g(x) = f(-x) - g(-x) \therefore h(x) \neq h(-x) \wedge h(x) \neq -h(-x)
\]
:::

::: {.theorem name="Decomposição em função par e ímpar"}
\(\forall h : \mathbb{R} \rightarrow \mathbb{R}\) com domínio simétrico em relação à origem, podemos definir as funções \(h_{\text{ímpar}} = h(x)-h(-x)\) e \(h_{\text{par}} = h(x)+h(-x)\) de modo que \(2h = h_{\text{par}} + h_{\text{ímpar}} \)
:::

::: {.proof}

**Parte 1:** Mostremos que \(h_{\text{par}}(x) = \frac{h(x) + h(-x)}{2}\) é par.

\[
h_{\text{par}}(-x) = \frac{h(-x) + h(--x)}{2} = \frac{h(-x) + h(x)}{2} = h_{\text{par}}(x)
\]

**Parte 2:** Mostremos que \(h_{\text{impar}}(x) = \frac{h(x) - h(-x)}{2}\) é ímpar.

\[
h_{\text{impar}}(-x) = \frac{h(-x) - h(--x)}{2} = \frac{h(-x) - h(x)}{2} = -\frac{h(x) - h(-x)}{2} = -h_{\text{impar}}(x)
\]

**Parte 3:** Soma das partes par e ímpar:

\[
h_{\text{par}}(x) + h_{\text{impar}}(x) = \frac{h(x) + h(-x)}{2} + \frac{h(x) - h(-x)}{2} = \frac{2h(x)}{2} = h(x)
\]

Logo,

\[
h(x) = \frac{h(x) + h(-x)}{2} + \frac{h(x) - h(-x)}{2}
\]

:::
